### ISSUE TITLE
Update cob_scenario_states

### ISSUE THREAD

**Issue by ipa-fxm** [ipa320/cob_scenario_states#8]
- [x] get updates from all forks
 - [x] catkinize (found on @ipa-rmb's fork :point_right: just needs some more cleanup)
 - [x] review what still works
 - [x] replace outdated/deprecated packages (e.g. kinematic_msgs, pr2*, ....)
 - [x] make proper python modules (see [here](http://docs.ros.org/jade/api/catkin/html/howto/format2/installing_python.html) and [here](http://docs.ros.org/jade/api/catkin/html/user_guide/setup_dot_py.html))

needed for https://github.com/ipa320/cob_tutorials/issues/2

**Comment by fmessmer** [comment]
all other bullet points are started on my [branch](https://github.com/ipa-fxm/cob_scenario_states/tree/fix_cob_scenario_states)

**Comment by floweisshardt** [comment]
we should makr cob_scenario_states as a deprecated repository. As far as I know, it is not actively used and thus not worth the effort in diving into it.

**Comment by fmessmer** [comment]
It is used in cob_tutorials!
And i can use it to give @ipa-bfb an intro on our CodingGuidelines...

I'll spent half a day more and see what we can do with it...and remove from indigo_dev branch rigorously what is outdated/not portable...
Merging all the developments from the various forks was definitely worth...even just for backup purposes...

**Comment by ipa-rmb** [comment]
I am using it. How do you nowadays write your SMACH scripts? Don't you have dependencies to this repository? Is there something new that is used now?

Connected to cob_map_accessibility_analysis there are several useful states that my students and me are using.

**Comment by fmessmer** [comment]
It's all there now!
refactored and cleaned up to the best of my knowledge and to the extent of effort-worthiness...

...now we would need to see how that helps to get `cob_tutorials` working again!

**Comment by bbrito** [comment]
Well I downloaded the updated cob_scenario_states and I got an error will running catkin_make. The error is still because of the dependencies with other packages as: 'cob_object_fake_detection'.

 -- Using these message generators: gencpp;genlisp;genpy
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by
  "cob_object_detection_fake" with any of the following names:

```
cob_object_detection_fakeConfig.cmake
cob_object_detection_fake-config.cmake
```

**Comment by fmessmer** [comment]
Did you download all the packages in the new rosinstall file (https://github.com/ipa-fxm/cob_tutorials/blob/fix_cob_tutorials/tutorials.rosinstall)
Seems like you do not have https://github.com/ipa320/cob_object_perception in your workspace...(this repository is not released yet)

**Comment by bbrito** [comment]
Yes. I got the following error when installing the rosdep:

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cob_map_accessibility_analysis: Cannot locate rosdep definition for [cob_3d_mapping_common]

**Comment by fmessmer** [comment]
Are you using the correct branches?
Note, this PR is not yet merged, thus, you need to `git checkout`:
https://github.com/ipa-fxm/cob_scenario_states/tree/fix_cob_scenario_states
https://github.com/ipa-fxm/cob_tutorials/tree/fix_cob_tutorials
